### Use dataset api from now on

based on this blog: https://towardsdatascience.com/how-to-use-dataset-in-tensorflow-c758ef9e4428 

And this notebook: https://github.com/FrancescoSaverioZuppichini/Tensorflow-Dataset-Tutorial/blob/master/dataset_tutorial.ipynb 

In [1]:
import tensorflow as tf
import numpy as np

1. simpliest way 

In [16]:
# using two numpy arrays# using 
features, labels = (np.random.sample((5,2)), np.random.sample((5,1)))
dataset = tf.data.Dataset.from_tensor_slices((features,labels))

iter = dataset.make_one_shot_iterator()  ## only do it once 
el = iter.get_next()

with tf.Session() as sess:
    for i in range(x.shape[0]):     ## if run iter more then x length, it will raise an error
        print(sess.run(el))

(array([0.73046059, 0.82241087]), array([0.06475445]))
(array([0.36386942, 0.59500756]), array([0.52754119]))
(array([0.38290554, 0.34082215]), array([0.87331317]))
(array([0.14258742, 0.30418836]), array([0.45359017]))
(array([0.26283525, 0.18944953]), array([0.00837901]))


2. using a tensor# using 

In [17]:
## from an tensor
dataset = tf.data.Dataset.from_tensor_slices(tf.random_uniform([100, 2]))

iter = dataset.make_initializable_iterator()
el = iter.get_next()

with tf.Session() as sess:
    sess.run(iter.initializer)
    print(sess.run(el))

[0.5634477 0.4006592]


### 3. using a placeholder and make it initialiable 

In case we want to build a dynamic dataset in which we can change the data sourceat runtime, we can create a dataset with a placeholder. Then we can initialize the placeholder using the common feed-dict mechanism. This is done with an initializable iterator. 

In [18]:

# initializable iterator to switch between data# initi 
EPOCHS = 10

x, y = tf.placeholder(tf.float32, shape=[None,2]), tf.placeholder(tf.float32, shape=[None,1])
dataset = tf.data.Dataset.from_tensor_slices((x, y))

train_data = (np.random.sample((100,2)), np.random.sample((100,1)))
test_data = (np.array([[1,2]]), np.array([[0]]))

iterator = dataset.make_initializable_iterator()
features, labels = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer, feed_dict={ x: data })
    print(sess.run(el))

[0.26172185 0.21336052]
